on: push

defaults:
  run:
    shell: bash

jobs:   
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: installing
        run: bash ./iterative/scr/init.sh
      - name: boot iterative
        run: |
          bash ./iterative/scr/build.sh
          bash ./iterative/scr/val.sh
      - name: boot parallel
        run: |
          bash ./parallel/scr/build.sh
          bash ./parallel/scr/val.sh
      - name: compare
        run: bash ../find_diff.sh
